-- Import Lua modules

require("packer_init")
require("core.autocmds")
require("core.commands")
require("core.keymaps")
require("core.netrw")
require("core.options")
require("core.statusline")
require("plugins.autotag")
require("plugins.devicons")
require("plugins.lsp")
require("plugins.mini")
require("plugins.nvim-cmp")
require("plugins.null-ls")
require("plugins.nvim-treesitter")
require("plugins.telescope")
