require("plugins.mini.ai")
require("plugins.mini.comment")
require("plugins.mini.jump")
require("plugins.mini.pairs")
require("plugins.mini.starter")
require("plugins.mini.statusline")
require("plugins.mini.surround")
