require("plugins.mini.starter")
require("plugins.mini.surround")
require("plugins.mini.ai")
require("plugins.mini.jump")
require("plugins.mini.jump2d")
require("plugins.mini.comment")
require("plugins.mini.pairs")
require("plugins.mini.statusline")
